### PR TITLE
Note about promises not changing underlying architecture.

### PR DESCRIPTION
**Pull request by bucaran**
May seem like a ridiculous PR, but I have struggled a lot with promises until one day I finally understood that they were just a _pattern_, an _abstraction_, that allows you to better compose and architect your async code. 

The underlying architecture of the JavaScript implementation in the browser/node/etc., does _not_ change. Totally evident for the savvy ones :smile: , but it was not so much for me at first, reading buzz word after buzz word. 

Promises [are not a new](http://en.wikipedia.org/wiki/Futures_and_promises#cite_note-1) invention (it took me a while to realize this), and we could've been using them in the browser back in 1999, maybe.

I will send more PRs if I notice anything else and thank you for this wonderful resource.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Thanks

**Comment by ForbesLindesay** [comment]
It's great to get a perspective from someone relatively new to promises (it's easy to lose sight of what was difficult to begin with).

**Comment by bucaran** [comment]
I am a _kinesthetic_ learner (hope I spell that one right) so I need to do with my hands or write the code and sometimes even reinvent and reimplement my own version of things so as to understand what is really going on. Well, now you know what I am going to do next. Even if I fail, it's a fun way to learn your promises.

**Comment by ForbesLindesay** [comment]
Hopefully https://www.promisejs.org/implementing should prove useful :)

**Comment by bucaran** [comment]
:feelsgood: Oh, yeah.

**Pull request merged**
